# Generated by Django 4.2.5 on 2023-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_persondb_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdb',
            old_name='loc',
            new_name='name',
        ),
    ]
