# Generated by Django 4.2.5 on 2023-10-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_userdb_activitydb_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydb',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.userdb'),
        ),
    ]
