# Generated by Django 4.2.5 on 2023-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_userdb_name_alter_userdb_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervaldb',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='locationdb',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='persondb',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='scheduledb',
            name='activity',
        ),
        migrations.DeleteModel(
            name='ActivityDB',
        ),
        migrations.DeleteModel(
            name='IntervalDB',
        ),
        migrations.DeleteModel(
            name='LocationDB',
        ),
        migrations.DeleteModel(
            name='PersonDB',
        ),
        migrations.DeleteModel(
            name='ScheduleDB',
        ),
        migrations.DeleteModel(
            name='UserDB',
        ),
    ]
